/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.varmetek.chestcleaner;

import me.varmetek.chestcleaner.io.RegionIO;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.RandomAccessFile;

public class App {

    //driver file
    //driver --
    public static void main(String[] args) throws FileNotFoundException {
        RegionIO regionIO = new RegionIO();
        File read = args.length == 1 ? new File(args[0]): new File("data.bin");
        regionIO.load(new RandomAccessFile(read, "rw"));



    }
}
